### Numpy - make : python list보다 속도가 훨씬 빠르다 

- array : 행렬, 벡터를 만든다
- reshape : 행렬, 벡터의 형태를 바꾼다
- index
- zeros : 영행렬을 만든다
- ones : 일행렬을 만든다
- eye : 단위행렬을 만든다
- like
- empty : 비어 있는 행렬을 만들 때 사용한다
- arange : range와 똑같은 기능을 수행한다(그러나 속도가 훨씬 빠르다)
- linspace : 공간을 linspace로 분할한다
- logspace : 공간을 logspace로 분할한다
- random - rand, randn : python random 모듈과 다르다
- stack, concat : 2개 이상의 array를 합친다
- split : 나눈다
- sort : 분류한다

#### array

- ndim : 행렬의 차원
- shape : 행렬의 모양

In [2]:
import numpy as np

In [3]:
# 1차원 배열

array = np.array([0,1,2,3])
print(type(array), array)

<class 'numpy.ndarray'> [0 1 2 3]


In [4]:
# 2차원 배열

array = np.array([[0,1],[1,2],[2,3],])
print(array)

[[0 1]
 [1 2]
 [2 3]]


In [5]:
# 3차원 배열

array = np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],[[0,1,2,3],[4,5,6,7],[8,9,10,11]]])
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [6]:
print(array.ndim, array.shape)

3 (2, 3, 4)


#### reshape : 행렬의 모양을 바꿀 수 있다

In [7]:
na = np.array(range(1,9))
na

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
# 방법 1

na.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# 방법 2

rna = np.reshape(na, (2, 4))

In [10]:
# 전치행렬(Transpose)

rna.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### Index

- 행렬의 특정 위치 값 가져오기
- 행렬 자르기(slashing)
- 행렬의 특정 값 바꾸기

In [11]:
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [12]:
print(array[1][1][2])

6


In [13]:
print(array[0, 0, 3])

3


In [14]:
# slashing

result = array[0:,0:,0:]
result

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [38]:
# array 데이터 수정하기

data = np.array(range(5))
data

array([0, 1, 2, 3, 4])

In [52]:
# 하나씩 바꾸기
data[2] = 0
data

IndexError: index 2 is out of bounds for axis 0 with size 2

In [40]:
data

array([0, 1, 0, 3, 4])

In [53]:
# 한꺼번에 바꾸기(Broadcasting)
data[3:] = 2
data

array([[1, 2, 3],
       [4, 5, 0]])

In [54]:
# 2차원 데이터 한꺼번에 바꾸기

data = np.array([range(1,4),range(4,7)])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
data[1:,2:] = 0
data

array([[1, 2, 3],
       [4, 5, 0]])

#### zeros

- 영행렬을 만든다
- float 형이 기본적으로 만들어진다

In [58]:
# float

z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [59]:
# int

z = np.zeros(5, dtype = int)
z

array([0, 0, 0, 0, 0])

In [62]:
z = np.zeros((2, 3), dtype = int)
z

array([[0, 0, 0],
       [0, 0, 0]])

In [63]:
z = np.zeros((2, 3, 4), dtype = int)
z

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

#### ones

- 일행렬을 만든다

In [66]:
one = np.ones((2,3,4), dtype = int)
one

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

#### 단위행렬(Indentity Matrix)

- `eye({숫자})` 형태로 만든다

In [69]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### like

- 행렬 안 모든 데이터를 0, 1로 바꾸는 함수

In [74]:
np.ones_like(z)
z

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

#### empty

- 빈행렬 데이터를 만든다
- 안에 어떤 데이터가 들어갈지 알 수 없다

In [79]:
np.empty((3,3))

array([[3.10503618e+231, 1.49457403e-154, 1.33397724e-322],
       [2.12199579e-314, 2.12199579e-314, 2.19733489e-314],
       [2.19733488e-314, 2.19733488e-314, 3.75481214e-308]])

#### arange

- range와 사용법은 동일하나, 큰 데이터를 만들 때 속도가 더 빠르다
- `arange({시작}, {끝}, {간격})`

In [80]:
size = int(1E6)
size

1000000

In [81]:
%timeit for x in range(size): x ** 2
%timeit for x in np.arange(size): x ** 2

459 ms ± 14.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
278 ms ± 5.22 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [82]:
np.arange(5, 10, 2)

array([5, 7, 9])

#### linspace, logspace

In [86]:
# linspace

np.linspace(0, 100, 3, dtype = int)

array([  0,  50, 100])

In [87]:
np.linspace(0, 100, 5, dtype = int)

array([  0,  25,  50,  75, 100])

In [89]:
# logspace
# log10(x1) = 2, lox10(x2) = 3, log10(x3) = 4
# x1 : 100, x2 = 1000, x3 = 10000

np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

#### random

- seed : 랜덤값을 결정해주는 값이다
- rand : uniform(균등분포)하게 랜덤 값을 출력한다
- randn : gaussian(정규분포)로 랜덤 값을 출력한다
- randint : 랜덤한 정수형을 출력한다
- shuffle : 섞어주는 함수이다
- choice : 여러 개에서 선택하는 함수이다

In [27]:
np.random.seed(0)
rd = np.random.rand(10)
rd

array([0.78643746, 0.65614305, 0.92884461, 0.86244709, 0.69828045,
       0.99912062, 0.67904846, 0.81787752, 0.93664797, 0.78152298])

In [29]:
rd = np.random.rand(2, 10)
rd

array([[0.14650066, 0.33958775, 0.03857319, 0.3747053 , 0.2470682 ,
        0.40378359, 0.85918284, 0.38469164, 0.41594447, 0.2483998 ],
       [0.30745662, 0.65731586, 0.79623339, 0.5291651 , 0.95797697,
        0.97363178, 0.79400679, 0.88925408, 0.38389497, 0.82087422]])

In [30]:
rd = np.random.randn(2, 10)
rd

array([[-0.93558872,  1.13730547, -0.55414307,  0.3035288 , -0.7379326 ,
        -0.82433251,  0.81519579, -1.22402227, -1.43766576,  0.07793555],
       [-1.66630862,  1.82689921,  0.44170788,  0.28903556, -0.21584129,
        -0.93099959, -1.0301595 , -0.53384585,  0.29031661,  1.20189077]])

In [82]:
# randint 
# np.random.randint({가장 작은 수}, {가장 큰 수}) # 그러나 가장 큰 수는 포함하지 않는다

np.random.randint(1, 10)

2

In [96]:
np.random.randint(0, 100, (3,3))

array([[60, 37, 55],
       [42, 51, 40],
       [63, 84, 18]])

In [5]:
data = np.random.randint(5, size = (3,3)) 
data
# default paramter로 2번째에 high 값이 들어가야 하기 때문에, (3,3)이 행렬의 크기라는 것을 명시해주어야 한다

array([[1, 4, 0],
       [2, 0, 2],
       [1, 4, 0]])

In [103]:
# shuffle

np.random.shuffle(data)
data.shape, data

((3, 3), array([[4, 1, 4],
        [1, 4, 0],
        [3, 3, 1]]))

In [3]:
# choice

np.random.choice(5, 10, p = [0, 0, 0, 0.5, 0.5])

array([3, 3, 3, 3, 3, 4, 3, 4, 3, 4])

In [6]:
data

array([[1, 4, 0],
       [2, 0, 2],
       [1, 4, 0]])

In [11]:
# unique : 유니크한 값의 개수를 확인할 수 있다

index, count = np.unique(data, return_counts = True)
print(index)
print(count)

[0 1 2 4]
[3 2 2 2]


#### stack : 하나씩 쌓는 것

In [15]:
na1 = np.arange(1,7)
na2 = np.arange(7,13)
print(na1, na1.shape)
print(na2, na1.shape)

[1 2 3 4 5 6] (6,)
[ 7  8  9 10 11 12] (6,)


In [3]:
na3 = np.stack((na1, na2))
print(na3, na3.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] (2, 6)


In [24]:
# axis = 0 이면 가장 큰 차원에서 쌓는다
# axis가 1씩 증가할수록 작은 차원에서 분류하여 쌓는다

na4 = np.stack((na1, na2), axis = 0)
print(na4, na4.shape)
np.stack?

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] (2, 6)


In [19]:
na1 = np.array([[1, 2, 3], [4, 5, 6]])
na2 = np.array([[7, 8, 9], [10, 11, 12]])

na1, na2

(array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]]))

In [21]:
na3 = np.stack((na1, na2))
print(na3)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [22]:
na4 = np.stack((na1, na2), axis = 1)
print(na4)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [23]:
# vstack

ls = []
for idx in range(5):
    ls.append(range(idx, idx+3))
ls

[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [24]:
v_stack = np.vstack(ls)
v_stack

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [25]:
h_stack = np.hstack(ls)
h_stack

array([0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

In [34]:
# hstack에서도 각 벡터를 살리기 위해서는? 아예 별개로 만든다

ls3 = [list(range(7))[idx:idx + 3] for idx in range(5)]
ls3

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]

In [35]:
# newaxis

np.arange(5)[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

#### concatenate 결합

- 세로 결합시 열의 숫자가 같아야 한다
- 가로 결합시 행의 숫자가 같아야 한다

In [42]:
r1 = np.random.randint(10, size = (2,3))
r1

array([[9, 6, 4],
       [6, 3, 8]])

In [43]:
r2 = np.random.randint(10, size = (3,2))
r2

array([[3, 2],
       [7, 6],
       [9, 1]])

In [44]:
r3 = np.random.randint(10, size = (3,3))
r3

array([[8, 0, 7],
       [4, 6, 0],
       [7, 4, 2]])

In [45]:
np.concatenate((r1,r3))

array([[9, 6, 4],
       [6, 3, 8],
       [8, 0, 7],
       [4, 6, 0],
       [7, 4, 2]])

In [47]:
np.concatenate((r2,r3), axis = 1)

array([[3, 2, 8, 0, 7],
       [7, 6, 4, 6, 0],
       [9, 1, 7, 4, 2]])

In [48]:
np.concatenate?

#### split

In [49]:
np.split?

In [70]:
r = np.arange(10, 20)
r

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
r1 = np.split(r, [5])
r1 

[array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]

In [72]:
a1, a2, a3, a4, a5 = np.split(r, [2,4,6,8])
a1

array([10, 11])

In [55]:
# vsplit - 행렬을 수평으로 나눠준다

In [56]:
r = np.random.randint(10, size = (4,6))
r

array([[8, 4, 0, 8, 3, 7],
       [0, 0, 7, 9, 5, 7],
       [3, 1, 8, 1, 8, 3],
       [0, 3, 1, 5, 7, 9]])

In [59]:
r1, r2 = np.vsplit(r, [2])
r2

array([[3, 1, 8, 1, 8, 3],
       [0, 3, 1, 5, 7, 9]])

In [60]:
# hsplit - 행렬을 수직으로 나눠준다

In [61]:
r

array([[8, 4, 0, 8, 3, 7],
       [0, 0, 7, 9, 5, 7],
       [3, 1, 8, 1, 8, 3],
       [0, 3, 1, 5, 7, 9]])

In [63]:
r1, r2 = np.hsplit(r, [4])
r2

array([[3, 7],
       [5, 7],
       [8, 3],
       [7, 9]])

In [ ]:
# sort

In [74]:
r = np.random.randint(10, size = (3,3))
r

array([[3, 3, 7],
       [5, 8, 4],
       [0, 4, 4]])

In [80]:
# axis가 0이 아니면, 같은 행 안에서 가로로 분류

r.sort()
r

array([[0, 3, 4],
       [3, 4, 7],
       [4, 5, 8]])

In [81]:
# axis가 0이면, 같은 열 안에서 세로로 분류 

r.sort(axis = 0)
r

array([[0, 3, 4],
       [3, 4, 7],
       [4, 5, 8]])

In [83]:
r.sort?

In [84]:
# c_ : 가로로 합치기

np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [85]:
# r_ : 가로로 합치기 
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [86]:
# stack, concatenate가 c_, r_ 보다 빠르다