### Quiz

In [1]:
import numpy as np

##### 1. 5개의 1로 이루어진 정수데이터 타입의 벡터를 만드세요

In [2]:
np.array([1, 1, 1, 1, 1])

array([1, 1, 1, 1, 1])

##### 2. 10개의 1로 이루어진 정수 데이터 타입의 벡터에서 마지막 3개의 데이터는 5가 들어있는 벡터를 만드세요

In [4]:
np.array([1, 1, 1, 1, 1, 1, 1, 5, 5,])

array([1, 1, 1, 1, 1, 1, 1, 5, 5])

##### 3. 10에서 20까지의 데이터를 가지는 벡터를 만드세요

In [5]:
np.arange(10, 21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

##### 4. 위 벡터의 순서를 바꾸세요

In [18]:
A = np.arange(10, 21)
A[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

##### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요

In [25]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 6. 위의 벡터에서  `[[4,5],[7,8]]`  행렬을 만드세요

In [44]:
x[1:, 1:]

array([[4, 5],
       [7, 8]])

##### 7. 1에서 10까지의 데이터를 랜덤하게 가지는 3*4 행렬을 만드세요

In [66]:
A = np.random.randint(1, 11, (3, 4))
A

array([[6, 2, 3, 2],
       [7, 4, 7, 8],
       [3, 7, 7, 3]])

##### 8. 위에서 만든 행렬의 unique 한 숫자들 리스트와 각숫자의 갯수를 리스트로 나타내세요

In [112]:
index, count = np.unique(A, return_counts = True)
index, count

(array([2, 3, 4, 6, 7, 8]), array([2, 3, 1, 1, 4, 1]))

##### 9. 1에서 12까지에 숫자가 들어간 3*4 행렬을 만드시고 행과 열에 관계없이 데이터를 섞으세요

In [77]:
x = np.arange(1, 13).reshape(3, 4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
np.random.shuffle(x)
x

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

##### 10. 1부터 10까지의 랜덤한 데이터가 들어가는 `3*3`행렬을 만드시고 가장 아래에 위의 데이터를 모두 합한 `1*3`행렬을 추가해서 `4*3`행렬을 만드세요

In [90]:
x = np.random.randint(1, 11, (3, 3))
x

array([[7, 5, 6],
       [6, 8, 1],
       [8, 2, 8]])

In [97]:
y = x[0] + x[1] + x[2]
y

array([21, 15, 15])

In [99]:
w = np.vstack((x, y))
w

array([[ 7,  5,  6],
       [ 6,  8,  1],
       [ 8,  2,  8],
       [21, 15, 15]])

##### 11. 10번문제의 결과로 나온 행렬데이터에서 평균값을 출력하고 평균값보다 큰 숫자들만 유니크한 리스트로 나열하세요 (평균값은 소수 둘째 자리까지만 나타내세요)

In [110]:
print(np.mean(w))
w > np.mean(w)

8.5


array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [106]:
w[w > np.mean(w)]

array([21, 15, 15])

##### 12. 1부터 20까지의 랜덤숫자를 가지는 5*5 행렬을 만드시고 최대값에는 숫자(MAX), 최소값에는 숫자(MIN)으로 행렬을 바꾸세요

In [412]:
v = np.random.randint(1, 21, (5,5))
v

array([[17,  7,  3, 11, 10],
       [13, 14,  9,  2,  2],
       [13,  3,  8,  4,  6],
       [ 7, 13,  5,  7,  1],
       [14, 10, 17,  6,  2]])

In [413]:
w = v.astype(str)
w

array([['17', '7', '3', '11', '10'],
       ['13', '14', '9', '2', '2'],
       ['13', '3', '8', '4', '6'],
       ['7', '13', '5', '7', '1'],
       ['14', '10', '17', '6', '2']], dtype='<U21')

In [414]:
w[v == v.max()] = str(v.max()) + '(MAX)'
w[v == v.min()] = str(v.min()) + '(MIN)'
w

array([['17(MAX)', '7', '3', '11', '10'],
       ['13', '14', '9', '2', '2'],
       ['13', '3', '8', '4', '6'],
       ['7', '13', '5', '7', '1(MIN)'],
       ['14', '10', '17(MAX)', '6', '2']], dtype='<U21')

##### 13. 100에서 130까지의 랜덤 숫자를 가지는 8*8행렬을 만드시고 3의 배수에는 fiz, 5의 배수에는 buz, 3과 5의 배수는 fbz 문자를 출력하세요

In [400]:
v = np.random.randint(100, 131, (8,8))
v

array([[113, 116, 121, 112, 125, 102, 125, 126],
       [129, 122, 115, 122, 112, 112, 104, 116],
       [130, 102, 125, 129, 125, 122, 116, 115],
       [112, 109, 128, 127, 130, 121, 114, 124],
       [111, 106, 105, 112, 103, 116, 124, 117],
       [122, 111, 109, 104, 129, 108, 114, 111],
       [121, 101, 128, 130, 124, 114, 107, 130],
       [127, 123, 126, 104, 107, 108, 119, 123]])

In [406]:
w = v.astype(str)
w

array([['113', '116', '121', '112', '125', '102', '125', '126'],
       ['129', '122', '115', '122', '112', '112', '104', '116'],
       ['130', '102', '125', '129', '125', '122', '116', '115'],
       ['112', '109', '128', '127', '130', '121', '114', '124'],
       ['111', '106', '105', '112', '103', '116', '124', '117'],
       ['122', '111', '109', '104', '129', '108', '114', '111'],
       ['121', '101', '128', '130', '124', '114', '107', '130'],
       ['127', '123', '126', '104', '107', '108', '119', '123']],
      dtype='<U21')

In [408]:
w[(v % 3 == 0) & (v % 5 == 0)] = 'fbz'
w[v % 3 == 0] = 'fiz'
w[v % 5 == 0] = 'buz'
w

array([['113', '116', '121', '112', 'buz', 'fiz', 'buz', 'fiz'],
       ['fiz', '122', 'buz', '122', '112', '112', '104', '116'],
       ['buz', 'fiz', 'buz', 'fiz', 'buz', '122', '116', 'buz'],
       ['112', '109', '128', '127', 'buz', '121', 'fiz', '124'],
       ['fiz', '106', 'buz', '112', '103', '116', '124', 'fiz'],
       ['122', 'fiz', '109', '104', 'fiz', 'fiz', 'fiz', 'fiz'],
       ['121', '101', '128', 'buz', '124', 'fiz', '107', 'buz'],
       ['127', 'fiz', 'fiz', '104', '107', 'fiz', '119', 'fiz']],
      dtype='<U21')

##### 14. 리스트 컴프리헨션을 이용하여 아래와 같은 규칙은 갖는 행렬을 만드세요

In [370]:
n = input("number : ")
np.array([[i * j for j in range(1, int(n) + 1)] for i in range(1, int(n) + 1)])

number : 9


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

### Quiz II

##### 7. 보어 구하기
- complement (보어)를 구하시오
- 50의 이진수는 110010
- 이진수 110010의 보어는 001101 (0을 1로바꾸고 1을 0으로 바꿈)
- 입력된 숫자의 보어를 10진수로 나타내시오

결과 예시
- 50 -> 13
- 100 -> 27

힌트
- 10진수를 2진수로 변환 : bin(n)
- 2진수를 10진수로 변환 : int(n,2)

xor - ^

In [291]:
number = 50
a = bin(number)
b = ""

for i in range(len(a)):
    if a[i] == "1":
        b += "0"
    elif a[i] == "0":
        b += "1" 
    else:
        b += a[i]
b

'1b001101'

In [292]:
int(b[2:], 2)

13

In [293]:
# 문자열
number = 100
a = bin(number)
b = ""

for i in range(len(a)):
    if a[i] == "1":
        b += "0"
    elif a[i] == "0":
        b += "1" 
    else:
        b += a[i]

result = int(b[2:], 2)
result

27

In [2]:
# XOR 비트연산자 ^
number = 100
# TODO
result

27

##### 8. Bit Manipulation: Lonely Integer
- https://www.hackerrank.com/challenges/ctci-lonely-integer/problem
- 리스트에 하나만 있는 데이터 찾아내서 출력하기
- ls 리스트에 있는 데이터의 카운트를 세서 딕셔너리 형태로 바꿔줌
```
from collections import Counter 
d = dict(Counter(ls))
```
- [1,1,2,2,3] (입력) -> 3 (결과)
- [1,1,2,2] (입력) -> None (결과)

In [302]:
from collections import Counter

ls = [1,1,2,5,2,3,9,23]
d = dict(Counter(ls))
d

result = []

for key, value in d.items():
    if value == 1:
        result.append(key)

result.sort()
result

[3, 5, 9, 23]

##### 9. Recursion: Fibonacci Numbers
- https://www.hackerrank.com/challenges/ctci-fibonacci-numbers/problem
- 피보나치 수열 초기값 a=0, b=1 에서 a는 b값이 되고 b는 a+b가 되는 a를 나열한 수열

In [349]:
# n 번째 피보나치 수열의 숫자
n = 10
a, b = 0, 1
for i in range(1, n):
    a, b = b, a + b
a

34

In [347]:
# n 까지 피보나치 수열의 숫자들
# TODO
def fib(n):
    a, b = 0, 1
    for i in range(n):
        print(a)
        a, b = b, a + b
        if a > 1000:
            break
fib(1000)

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987


##### 10. 피보나치킨
- 모르겠습니다.
- http://fibonachicken.herokuapp.com/

```
사람, 치킨, 피보나치수
1  1  -
2  1  -
3  2  -
4  3
5  3  -
6  4
7  4
8  5  -
9  6
10 6
11 7
12 8
13 8  -
14 9 
15 9
16 10
17 11
18 11
19 12
20 12
21 13 -
```

In [44]:
def is_fib(num):
    # TODO
def prev_fib(num):
    # TODO

In [45]:
def fib_chicken(person):
    # TODO

In [46]:
is_fib(13), is_fib(17), is_fib(21)

(True, False, True)

In [47]:
prev_fib(13), prev_fib(17), prev_fib(21)

(8, 13, 13)

In [50]:
fib_chicken(42)

26