### Numpy - Caculate

- 기본연산
- 브로드캐스팅
- 함수
- 퍼포먼스

#### 기본연산

In [1]:
# list

ls = [1, 2, 3]
ls * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
%%timeit
ls = [1, 2, 3]
ls = [num * 3 for num in ls]
ls

604 ns ± 15 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
%%timeit
na = np.array([1,2,3])
na * 3

2.9 µs ± 31.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
na1 = np.array([1,2,3])
na2 = np.array([4,5,6])
na1 * na2 # ndarray의 연산 값 "*"이 list의 *과 다르게 적용되기 때문이다

array([ 4, 10, 18])

In [10]:
# 비교연산

na1 == 2, na2 > 5

(array([False,  True, False]), array([False, False,  True]))

In [17]:
na1 = np.array(range(1,10))
is3 = na1 % 3 == 0

In [21]:
na1 = np.array(range(1,10))
na1[is3]

array([3, 6, 9])

#### 브로드 캐스팅

- ndarray에 연산을 하면, 모든 요소(element)에 연산이 수행된다

In [26]:
na1 = np.arange(12)
na2 = na1.reshape(3, 4)
na3 = np.ones((3, 4), dtype = int)

print(na1)
print(na2)
print(na3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [30]:
na2 ** 2 + na2

array([[  0,   2,   6,  12],
       [ 20,  30,  42,  56],
       [ 72,  90, 110, 132]])

In [31]:
# row에 대한 브로드캐스팅

na4 = np.arange(4)
print(na4)

[0 1 2 3]


In [32]:
na2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
na2 + na4

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [41]:
# column에 대한 브로드캐스팅

na5 = np.arange(3)[:, np.newaxis]
na5, na5.shape

(array([[0],
        [1],
        [2]]), (3, 1))

In [42]:
na5 + na2

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

#### functions

- min, max : 행렬의 최소값, 최대값을 출력한다
- argmin, argmax : argmin, argmax는 각 데이터 값의 index를 출력한다
- sum, mean, median, std, var : 합, 평균(기대값), 중간값, 표준편차, 분산을 출력한다
- all, any : 
- quartile : 
- exp, log : 

In [59]:
r = np.random.randint(10, size = (2,3))
r

array([[4, 2, 8],
       [7, 3, 3]])

In [60]:
r.min(), r.max(), r.argmin(), r.argmax() 

(2, 8, 1, 2)

In [61]:
r.mean(), np.sum(r) / 6

(4.5, 4.5)

In [62]:
np.sum(r, axis = 0) # axis가 0일 때는 가장 큰 차원에서 함수를 실행하여 출력한다

array([11,  5, 11])

In [63]:
np.sum(r, axis = 1)

array([14, 13])

In [64]:
np.median(r), np.std(r), np.var(r)

(3.5, 2.217355782608345, 4.916666666666667)

In [66]:
# all - 모든 조건이 충족하면 True (& 와 비슷하다)
# any - 하나의 조건만 충족해도 True(O) (or 과 비슷하다)

In [68]:
n1 = np.array(range(3, 8))
n2 = n1
n3 = np.array([3, 4, 0, 6, 7])

In [70]:
n1 == n2, np.all(n1 == n2), np.any(n1 == n2)

(array([ True,  True,  True,  True,  True]),
 array([ True,  True, False,  True,  True]))

In [71]:
n3 == n2, np.all(n3 == n2), np.any(n3 == n2)

(array([ True,  True, False,  True,  True]), False, True)

#### 사분위수
- 특정 위치에 있는 값을 가져올 수 있다
- 예 : 전체 표본값 중 중 n% 위치에 있는 값을 가져오고자 할 때 쓴다

In [80]:
na = np.arange(100, 201)
print(na)
np.percentile(na, 25), 

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]


(125.0,)

#### 지수함수, 로그함수

- 지수함수 : 수치가 너무 작아 스케일을 키우고 싶을 때 활용한다
- 로그함수 : 수치가 너무 커 스케일을 줄이고 싶을 때 활용한다

In [86]:
# 지수함수

na = np.arange(1, 6)
print(na)
np.exp(na)

[1 2 3 4 5]


array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [87]:
# 로그함수

np.log(na)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

#### 퍼포먼스 차이 비교(python vs. numpy)

In [88]:
# 10 **

In [92]:
%%time
ls = []
size = int(10E5)
for data in range(size):
    ls.append(data)
len(ls)

CPU times: user 2.34 s, sys: 4.45 s, total: 6.79 s
Wall time: 6.83 s


In [93]:
%%time
la = np.arange(size)
len(la)

CPU times: user 4.07 ms, sys: 3.96 ms, total: 8.03 ms
Wall time: 5.94 ms


In [95]:
%%time
count = len(la[(la % 3 == 0) | (la % 5 == 0)])
count

CPU times: user 55.5 ms, sys: 5.09 ms, total: 60.6 ms
Wall time: 59.4 ms
