In [28]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import make_blobs
X, y = make_blobs(n_samples=50, centers=2, cluster_std=0.5, random_state=4)
y = 2 * y - 1

In [4]:
from sklearn.svm import SVC
model = SVC(kernel='linear', C=1e10).fit(X, y)

In [5]:
model.n_support_

array([1, 1], dtype=int32)

In [6]:
model.support_

array([42,  1], dtype=int32)

In [7]:
model.support_vectors_

array([[9.03715314, 1.71813465],
       [9.17124955, 3.52485535]])

In [8]:
y[model.support_]

array([-1,  1])

In [9]:
x_new = [10, 2]
model.decision_function([x_new])

array([-0.61101582])

In [ ]:
model.coef_.dot(x_new) + model.

In [10]:
# dual_coef = a_i * y_i

model.dual_coef_

array([[-0.60934379,  0.60934379]])

In [11]:
model.dual_coef_[0][0] * model.support_vectors_[0].dot(x_new) + \
model.dual_coef_[0][1] * model.support_vectors_[1].dot(x_new) + \
model.intercept_

array([-0.61101582])

In [ ]:
# 연습 문제 1
# 붓꽃 문제를 서포트 벡터 머신으로 풀어보자. 
# 다음과 같은 데이터만 사용한 이진 분류 문제로 바꾸어 풀어본다. 
# 위의 예제와 마찬가지로 커널 인수 kernel과 슬랙 변수 가중치 인수 C는
# 각각 linear, 1e10으로 한다.

In [58]:
from sklearn.datasets import load_iris
iris = load_iris()

In [84]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
sy = pd.Series(iris.target, dtype="category")
sy = sy.cat.rename_categories(iris.target_names)
df['species'] = sy
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica

In [85]:
df = df[:100]
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
95                1.0               1.0                1.0               1.0   
96                1.0               1.0                1.0               1.0   
97                1.0               1.0                1.0               1.0   
98                1.0               1.0                1.0               1.0   
99                1.0               1.0                1.0               1.0   

       species  
95  versicolor  
96  versicolor  
97  versicolor  
98  versicolor  
99  versicolor

In [86]:
df['species'].replace(to_replace='setosa', value='0', inplace=True)
df['species'].replace(to_replace='versicolor', value='1', inplace=True)

In [70]:
df['species'].astype('int', inplace=True)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
     ..
70    1
71    1
72    1
73    1
74    1
75    1
76    1
77    1
78    1
79    1
80    1
81    1
82    1
83    1
84    1
85    1
86    1
87    1
88    1
89    1
90    1
91    1
92    1
93    1
94    1
95    1
96    1
97    1
98    1
99    1
Name: species, Length: 100, dtype: int64

In [71]:
df.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
species                int64
dtype: object

In [72]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
95                1.0               1.0                1.0               1.0   
96                1.0               1.0                1.0               1.0   
97                1.0               1.0                1.0               1.0   
98                1.0               1.0                1.0               1.0   
99                1.0               1.0                1.0               1.0   

    species  
95        1  
96        1  
97        1  
98        1  
99        1

In [74]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
95                1.0               1.0                1.0               1.0   
96                1.0               1.0                1.0               1.0   
97                1.0               1.0                1.0               1.0   
98                1.0               1.0                1.0               1.0   
99                1.0               1.0                1.0               1.0   

    species  
95        1  
96        1  
97        1  
98        1  
99        1

In [76]:
X = df.iloc[:, :2]
y = df['species']
y.tail()

95    1
96    1
97    1
98    1
99    1
Name: species, dtype: int64

In [77]:
model = SVC(kernel='linear', C=1e10).fit(X, y)

In [78]:
model.n_support_

array([1, 1], dtype=int32)

In [79]:
model.support_vectors_

array([[0., 0.],
       [1., 1.]])

In [83]:
X[y == ]

sepal length (cm)  sepal width (cm)
0                 0.0               0.0
1                 0.0               0.0
2                 0.0               0.0
3                 0.0               0.0
4                 0.0               0.0
5                 0.0               0.0
6                 0.0               0.0
7                 0.0               0.0
8                 0.0               0.0
9                 0.0               0.0
10                0.0               0.0
11                0.0               0.0
12                0.0               0.0
13                0.0               0.0
14                0.0               0.0
15                0.0               0.0
16                0.0               0.0
17                0.0               0.0
18                0.0               0.0
19                0.0               0.0
20                0.0               0.0
21                0.0               0.0
22                0.0               0.0
23                0.0               0.0
24                0.0               0.0
25                0.0               0.0
26                0.0               0.0
27                0.0               0.0
28                0.0               0.0
29                0.0               0.0
..                ...               ...
70                1.0               1.0
71                1.0               1.0
72                1.0               1.0
73                1.0               1.0
74                1.0               1.0
75                1.0               1.0
76                1.0               1.0
77                1.0               1.0
78                1.0               1.0
79                1.0               1.0
80                1.0               1.0
81                1.0               1.0
82                1.0               1.0
83                1.0               1.0
84                1.0               1.0
85                1.0               1.0
86                1.0               1.0
87                1.0               1.0
88                1.0               1.0
89                1.0               1.0
90                1.0               1.0
91                1.0               1.0
92                1.0               1.0
93                1.0               1.0
94                1.0               1.0
95                1.0               1.0
96                1.0               1.0
97                1.0               1.0
98                1.0               1.0
99                1.0               1.0

[100 rows x 2 columns]

In [82]:
plt.scatter(X[y == -1, 0], X[y == -1, 1], marker='o')
plt.scatter(X[y == +1, 0], X[y == +1, 1], marker='x')
plt.show()


TypeError: 'Series' objects are mutable, thus they cannot be hashed

In [81]:
xmin = X[:,0].min()
xmax = X[:,0].max()
ymin = X[:,1].min()
ymax = X[:,1].max()
xx = np.linspace(xmin, xmax, 10)
yy = np.linspace(ymin, ymax, 10)
X1, X2 = np.meshgrid(xx, yy)

Z = np.empty(X1.shape)
for (i, j), val in np.ndenumerate(X1):
    x1 = val
    x2 = X2[i, j]
    p = model.decision_function([[x1, x2]])
    Z[i, j] = p[0]
levels = [-1, 0, 1]
linestyles = ['dashed', 'solid', 'dashed']
plt.scatter(X[y == -1, 0], X[y == -1, 1], marker='o')
plt.scatter(X[y == +1, 0], X[y == +1, 1], marker='x')
plt.contour(X1, X2, Z, levels, colors='k', linestyles=linestyles)
plt.scatter(model.support_vectors_[:, 0], 
            model.support_vectors_[:, 1], 
            s=300, alpha=0.3)

x_new = [10, 2]
plt.scatter(x_new[0], x_new[1], marker='^', s=100)

plt.show()

TypeError: unhashable type: 'slice'

In [80]:
plt.scatter(X[y == +1, 0], X[y == 0, 1], marker='o')
# plt.scatter(X[y == +1, 0], X[y == +1, 1], marker='x')
plt.show()

TypeError: 'Series' objects are mutable, thus they cannot be hashed

In [44]:
plt.scatter(X[y == -1, 0], X[y == -1, 1], marker='o')
plt.scatter(X[y == +1, 0], X[y == +1, 1], marker='x')
plt.show()

TypeError: 'Series' objects are mutable, thus they cannot be hashed